# Generated by Django 3.0 on 2020-04-16 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_recovery_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
