# Generated by Django 3.0 on 2020-04-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_profiles_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
                ('artwork_path', models.CharField(max_length=50)),
                ('contributing_artists', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('genere', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('year', models.DateField(verbose_name='Date')),
                ('size', models.IntegerField()),
                ('track_no', models.IntegerField(default=1)),
                ('album_artist', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('bitrate', models.CharField(max_length=50)),
                ('date_modified', models.DateField(verbose_name='Date')),
                ('tags', models.CharField(max_length=50)),
                ('parental_rating', models.CharField(max_length=50)),
                ('date_created', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
