# Generated by Django 3.0 on 2020-04-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='musics/')),
            ],
        ),
        migrations.RenameModel(
            old_name='song',
            new_name='metadata',
        ),
    ]
