# Generated by Django 3.0 on 2020-04-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200417_0841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='songs',
            new_name='song',
        ),
    ]
