# Generated by Django 3.0 on 2020-04-17 07:59

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200417_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('number_folder', models.CharField(max_length=250, verbose_name='Numero de Carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Case')),
            ],
        ),
    ]
