# Generated by Django 3.0 on 2020-04-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_case_casefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='case',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='CaseFile',
        ),
    ]
