# Generated by Django 3.0 on 2020-04-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_song_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
    ]
