# Generated by Django 3.0.5 on 2020-04-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='album',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='album_artist',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='artwork_path',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='bitrate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='contributing_artists',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='genere',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='parental_rating',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='path',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
