# Generated by Django 3.0.5 on 2020-04-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200418_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='song',
        ),
    ]
