# Generated by Django 3.0.5 on 2020-04-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_metadata_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='genere',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='path',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='tags',
        ),
        migrations.AddField(
            model_name='metadata',
            name='audio_offset',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='samplerate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
