# Generated by Django 3.0.5 on 2020-04-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20200418_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
