# Generated by Django 3.0.5 on 2020-04-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20200418_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
