# Generated by Django 3.0.5 on 2020-04-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20200418_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='parental_rating',
            field=models.IntegerField(default=0),
        ),
    ]
