# Generated by Django 3.0.5 on 2020-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20200418_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='track_total',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
