# Generated by Django 3.0.5 on 2020-04-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_metadata_track_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
