# Generated by Django 3.0.5 on 2020-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20200418_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='track_no',
            field=models.CharField(default=1, max_length=50, null=True),
        ),
    ]
