# Generated by Django 3.0.5 on 2020-04-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20200418_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='artwork_path',
            new_name='artwork_name',
        ),
    ]
