# Generated by Django 3.0.5 on 2020-04-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20200418_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='audio_offset',
        ),
    ]
