# Generated by Django 3.0.5 on 2020-04-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_remove_metadata_audio_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='file',
            field=models.FileField(null=True, upload_to='tmp/'),
        ),
    ]
