# Generated by Django 3.0.5 on 2020-04-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20200418_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='artwork_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
