# Generated by Django 3.0.5 on 2020-04-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_album'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='album',
            new_name='albums',
        ),
    ]
