# Generated by Django 3.0.5 on 2020-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_auto_20200419_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
