# Generated by Django 3.0.5 on 2020-04-19 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0034_albums_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='date_modified',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
