# Generated by Django 3.0.5 on 2020-04-19 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0035_albums_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50, null=True)),
                ('date_modified', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
