# Generated by Django 3.0.5 on 2020-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0036_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
