# Generated by Django 3.0.5 on 2020-04-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0037_artist_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.FileField(null=True, upload_to='tmp/artist'),
        ),
    ]
