# Generated by Django 3.0.5 on 2020-04-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0039_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='artist_search',
        ),
    ]
