# Generated by Django 3.0.5 on 2020-04-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0040_auto_20200420_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
