# Generated by Django 3.0.5 on 2020-04-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0041_modelwithimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(upload_to='tmp/artist'),
        ),
        migrations.AlterField(
            model_name='modelwithimage',
            name='image',
            field=models.ImageField(upload_to='tmp/artist'),
        ),
    ]
