# Generated by Django 3.0.5 on 2020-04-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0042_auto_20200420_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelWithImage',
        ),
    ]
