# Generated by Django 3.0.5 on 2020-04-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0043_delete_modelwithimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_img_original',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
