# Generated by Django 3.0.5 on 2020-04-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0047_metadata_total_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='length',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
