# Generated by Django 3.0.5 on 2020-04-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0049_auto_20200421_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='parental_rating',
            new_name='explicit',
        ),
    ]
