# Generated by Django 3.0.5 on 2020-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0051_auto_20200421_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='total_played',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='total_played',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='total_played',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
