# Generated by Django 3.0.5 on 2020-04-22 03:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0053_auto_20200421_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='total_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='total_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='total_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('metadata_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.metadata')),
                ('profiles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.profiles')),
            ],
        ),
    ]
