# Generated by Django 3.0.5 on 2020-04-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0054_auto_20200422_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='metadata_id',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='profiles_id',
            new_name='profiles',
        ),
    ]
