# Generated by Django 3.0.5 on 2020-04-22 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0055_auto_20200422_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='albums',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='music.albums'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='artist',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
            preserve_default=False,
        ),
    ]
