# Generated by Django 3.0.5 on 2020-04-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0056_auto_20200422_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='library',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='library',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='library',
            name='metadata',
        ),
    ]
