# Generated by Django 3.0.5 on 2020-04-22 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0057_auto_20200422_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='albums',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.albums'),
        ),
        migrations.AddField(
            model_name='library',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
        migrations.AddField(
            model_name='library',
            name='date_added',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='library',
            name='metadata',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.metadata'),
        ),
    ]
