# Generated by Django 3.0.5 on 2020-04-22 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0058_auto_20200422_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='albums',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.albums'),
        ),
        migrations.AlterField(
            model_name='library',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
        migrations.AlterField(
            model_name='library',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.metadata'),
        ),
    ]
