# Generated by Django 3.0.5 on 2020-04-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0061_auto_20200422_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='library',
        ),
    ]
