# Generated by Django 3.0.5 on 2020-04-22 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0063_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='recent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.metadata')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.profiles')),
            ],
        ),
    ]
