# Generated by Django 3.0.5 on 2020-04-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0065_auto_20200422_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent',
            name='albums',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.albums'),
        ),
        migrations.AddField(
            model_name='recent',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
    ]
