# Generated by Django 3.0.5 on 2020-04-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0067_auto_20200422_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='artist',
        ),
    ]
