# Generated by Django 3.0.5 on 2020-04-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0068_auto_20200422_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recent',
        ),
    ]
