# Generated by Django 3.0.5 on 2020-08-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0071_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='total_played',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
